In [ ]:
import numpy as np

#Numpy ile Nokta Doğru Düzlem ve Uzay

In [ ]:
skaler=np.array(90)
print(skaler)

90


In [ ]:
vektor=np.array([1,2,3,4,5,6])
print(vektor)

[1 2 3 4 5 6]


In [ ]:
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:

tensor = np.array([
    [[1,2,3], [4,5,6]],
    [[1,2,3], [4,5,6]],
    [[1,2,3], [4,5,6]]
])

print(tensor)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Neden Numpy ?

In [ ]:
# Bu işlemi numpy olmadan yapsaydık 100 kat daha yavaş sonuç alırdık.Yani numpy 100 kat hız kazandırır.
import time
z1=time.time()

liste1=np.arange(1_000_000)**100

z2=time.time()

print(z2-z1)


0.039199113845825195


#VEKTÖRLERDE index ve slice

In [ ]:
###index
vektor=np.array([1,2,3,4,5])
vektor[-1]

np.int64(5)

In [ ]:
###slice
vektor[1:4:2]

array([2, 4])

#size shape ndim dtype

In [ ]:
vektor=np.array([1,2,3,4,5,6,7,8,9])
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
vektor.size#eleman sayısını verir

9

In [ ]:
matris.size

9

In [ ]:
vektor.shape#burda tek boyutlu olduğu için eleman sayısı ve hiç bir şey yazmaz boyutsuz çünkü

(9,)

In [ ]:
matris.shape#burda 3 tane [] var onların içinde 3 tane eleman var o yüzden (3,3)

(3, 3)

In [ ]:
vektor.ndim#boyut sayısını verir

1

In [ ]:
matris.ndim

2

In [ ]:
vektor.dtype# elemanların tipini gösterir(numpy nin type() ı )

dtype('int64')

In [ ]:
matris.dtype

dtype('int64')

In [ ]:
type(vektor)

numpy.ndarray

In [ ]:
type(matris)

numpy.ndarray

# Numpy veri değiştirme

In [ ]:
sayilar=np.array([1,2,3,4,5,6,7,8,9],dtype="float64")
sayilar

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
sayilar=sayilar.astype("int32")
sayilar

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
tarih=np.array(["2025-04-27"])
tarih.dtype#çıktısı obje şeklinde olur

dtype('<U10')

In [ ]:
tarih=tarih.astype("datetime64")#tarih i tarih değişkenine atıyoruz işimiz kolay olsun
tarih.dtype

dtype('<M8[D]')

#MATRİSLERDE slice

In [ ]:
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
matris[0:3,0]#virgülün sol tarafı [] alır,sağ tarafıda onlaın içindekilerde işlem yapmaı sağlar.(sonuç 0 dan 3 e kadar alır.onların 0. elemanını yazdırır)

array([1, 4, 7])

In [ ]:
dir(np.random)#👉 dir() Python'da bir nesnenin içindeki tüm özellikleri (fonksiyonlar, değişkenler, vs.) listeleyen yerleşik (built-in) bir fonksiyondur.

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

# Random vektör ya da matris ya da diğer şeyler oluşturma

In [ ]:
np.random.randint(0,5)

4

In [ ]:
np.random.randint(0,5,(3,6))

array([[1, 2, 1, 1, 0, 3],
       [4, 3, 2, 1, 4, 4],
       [0, 1, 1, 0, 2, 1]])

In [ ]:
np.random.randint(0,5,(3,8))/10

array([[0.2, 0.3, 0.4, 0. , 0.2, 0.2, 0. , 0.3],
       [0.4, 0.1, 0. , 0.2, 0.1, 0.2, 0.2, 0. ],
       [0.4, 0. , 0.4, 0.2, 0.2, 0.4, 0.3, 0. ]])

# linspace reshape view copy

In [ ]:
np.linspace(0,10,5)#0 dan 10 a kadar(10 dahil burda) aralığı 5 eşit parçaya böler

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
m1=np.random.randint(0,20,(3,4))
m1

array([[ 8,  9, 15,  5],
       [ 4,  1, 13, 14],
       [15,  3,  7, 13]])

In [ ]:
m1.reshape(6,2)#tekrar boyutlandırır

array([[ 8,  9],
       [15,  5],
       [ 4,  1],
       [13, 14],
       [15,  3],
       [ 7, 13]])

In [ ]:
matris1=np.random.randint(0,20,(3,4))
matris2=matris1.view()#view matris1 i matris2 ye kopyalar.matris2 deki değişiklikler matris1 e etki eder.
matris2

array([[ 7,  7, 18, 11],
       [15,  6, 19,  7],
       [ 6, 19,  3, 19]])

In [ ]:
matris3=np.random.randint(0,20,(3,4))
matris4=matris3.copy()#view matris1 i matris2 ye kopyalar.matris2 deki değişiklikler matris1 e etki etmez.
matris4

array([[17,  2,  6,  1],
       [11, 11,  2,  3],
       [11, 12, 10,  3]])

In [ ]:
matris=np.ones((3,4))#1 le 3,4 lük matris oluşturur
matris

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
matris=np.zeros((4,5))#0 la 4,5 lik matris oluşturur
matris

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
matris=np.full((3,4),5)#5 le 3,4 lük matris oluşturur
matris

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

#eye diag identity

In [ ]:
np.identity(5)#5 lik birim matrisin 1 ile köşegenini oluşturur

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5,k=2)#5 lik birim matrisin 1 ile köşegenini oluşturur ama bunda köşegenin yerini ayarlayabilirsin(ters yön için - kullanıyon)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.diag([1,2,3,4,555])#köşegeni kendin ayarlıyon

array([[  1,   0,   0,   0,   0],
       [  0,   2,   0,   0,   0],
       [  0,   0,   3,   0,   0],
       [  0,   0,   0,   4,   0],
       [  0,   0,   0,   0, 555]])

In [ ]:
r=np.random.randint(0,10,(3,3))
r

array([[8, 4, 1],
       [7, 6, 7],
       [3, 4, 6]])

In [ ]:
np.diag(r)

array([8, 6, 6])

In [ ]:
np.diag(np.diag(r))#köşegenini aldık

array([[8, 0, 0],
       [0, 6, 0],
       [0, 0, 6]])

# 4 İŞLEM

In [ ]:
#pythonda bölmede sadece tam kısmını almak istiyorsan // kullanacan
5//2

2

In [ ]:
m1=np.random.randint(0,10,(3,3))
m2=np.random.randint(0,10,(3,3))

In [ ]:
m1+m2

array([[10, 13, 13],
       [ 9,  8, 10],
       [12, 15, 10]])

In [ ]:
m1*m2

array([[21, 40, 42],
       [14, 12,  9],
       [32, 54, 16]])

In [ ]:
m1/m2

array([[0.42857143, 0.625     , 0.85714286],
       [0.28571429, 0.33333333, 9.        ],
       [2.        , 0.66666667, 0.25      ]])

In [ ]:
m1//m2

array([[0, 0, 0],
       [0, 0, 9],
       [2, 0, 0]])

In [ ]:
m3=np.random.randint(0,10,(5,5))

In [ ]:
#matrisler aynı boyutta olmalı işlem yapabilmek için aynı boyuta eşitlemen lazım

In [ ]:
m3.reshape(25)[:9].reshape((3,3))+m2

array([[16,  8, 11],
       [13,  7,  8],
       [ 8, 13,  9]])

#Numpy ile Mantıksal operatörler ve filtreleme

In [ ]:
#numpyde pythondaki and or not yerine & | ~ kullanılır

In [ ]:
m1=np.random.randint(2,10,(3,4))

In [ ]:
m1[m1%2==0]#böyle çıktıları dizi olarak verir

array([6, 4, 2, 8, 2, 8, 8])

In [ ]:
cift=m1%2==0
tek=~cift


In [ ]:
m1[cift]

array([6, 4, 2, 8, 2, 8, 8])

In [ ]:
m1[tek]

array([9, 3, 9, 7, 3])

In [ ]:
#böyle oluşturabilirsin